### ISSUE TITLE
cache_type variable seems to have become a mandatory variable

### ISSUE THREAD

**Issue by besmirzanaj** [riemers/ansible-gitlab-runner#101]
cache_type variable seems to have become mandatory after this https://github.com/riemers/ansible-gitlab-runner/commit/5c9659ba1e6c31442c02f066357359c4bdfe03a9

`TASK [riemers.gitlab-runner : Set cache s3 section] *******************************************************************************************************
Wednesday 12 February 2020  14:49:14 -0500 (0:00:00.591)       0:01:40.354 **** 
fatal: [vps3.cloudalbania.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'cache_type'\n\nThe error appears to be in '/home/bzanaj/git/pers/ansible-systems/roles/riemers.gitlab-runner/tasks/update-config-runner.yml': line 128, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set cache s3 section\n  ^ here\n"}
`

**Comment by besmirzanaj** [comment]
tests are not failing as this variable is already present there

`14:58 $ grep cache_type roles/riemers.gitlab-runner/tests/vars/default.yml
    cache_type: s3
    cache_type: gcs
`

**Comment by riemers** [comment]
Could you try changing the "when" items to
```
when: gitlab_runner.cache_type is defined and gitlab_runner.cache_type == 's3'
```
And one for gcs
```
when: gitlab_runner.cache_type is defined and gitlab_runner.cache_type == 'gcs'
```
And see if that resolves the issue, if so i can adjust it.

**Comment by besmirzanaj** [comment]
testing

**Comment by besmirzanaj** [comment]
changed the following to the recommended lines but the issue still persists

https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/update-config-runner.yml#L228
https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/update-config-runner.yml#L264

**Comment by riemers** [comment]
My bad..

change that line to:
```
state: "{{ 'present' if gitlab_runner.cache_type is defined else 'absent' }}"
```

**Comment by besmirzanaj** [comment]
ok, testing

**Comment by besmirzanaj** [comment]
now it complains for another section, line 218

`TASK [riemers.gitlab-runner : Set cache s3 bucket name option] ********************************************************************************************
Wednesday 12 February 2020  16:06:46 -0500 (0:00:00.709)       0:01:53.505 **** 
fatal: [vps3.cloudalbania.com]: FAILED! => {"msg": "The conditional check 'gitlab_runner.cache_type == 's3'' failed. The error was: error while evaluating conditional (gitlab_runner.cache_type == 's3'): 'dict object' has no attribute 'cache_type'\n\nThe error appears to be in '/home/bzanaj/git/pers/ansible-systems/roles/riemers.gitlab-runner/tasks/update-config-runner.yml': line 218, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set cache s3 bucket name option\n  ^ here\n"}
`

**Comment by riemers** [comment]
Do you still have the adjusted "when" options in there?

**Comment by besmirzanaj** [comment]
no I removed them, should I add them back?

**Comment by riemers** [comment]
yes please, not sure if it will fix just trying to work with you. But seems logical since it is checking for a var that is not set. So we should not have to check for it.

**Comment by tauffredou** [comment]
Hi, I'm looking at the issue. I agree with @riemers , checking for presence should fix this.

**Comment by besmirzanaj** [comment]
both changes fixed the issue. will send a pull request

**Comment by besmirzanaj** [comment]
https://github.com/riemers/ansible-gitlab-runner/pull/102

**Comment by riemers** [comment]
Merged it, time for 🛏 if there are any issues just re-open.
