### ISSUE TITLE
add the ability to set *dns* and *tls_verify* option

### ISSUE THREAD

**Issue by haghighi-ahmad** [riemers/ansible-gitlab-runner#104]
The `dns` and `tls_verify` option missing.   
Sometimes we should use custom DNS per Job (executor) or mybe we use an internal Docker registry with self signed certificate, so I think its useful to add them.

**Comment by haghighi-ahmad** [comment]
related MR: https://github.com/riemers/ansible-gitlab-runner/pull/105

**Comment by riemers** [comment]
Thats ok, if it is needed people can always add it ;p
