### ISSUE TITLE
Does not update to latest version

### ISSUE THREAD

**Issue by justfortherec** [riemers/ansible-gitlab-runner#134]
When re-running a playbook with the `gitlab-runner` role, the version of the deployed runner is not updated to the lastest version.

I understand from documentation, that this should be the case. The README says (emphasis added):
> * `gitlab_runner_wanted_version` or `gitlab_runner_package_version` - To install a specific version of the gitlab runner **(by default it installs the latest).** On Mac OSX and Windows, use e.g. `gitlab_runner_wanted_version`: 12.4.1. On Linux, use `gitlab_runner_package_version` instead.

Are there any caveats? (or is this my user error?)

The runner had been originally deployed with `gitlab-runner` 1.2.3 and I have tried re-deploying with the same version and the latest 1.6.17.

**Comment by justfortherec** [comment]
The problem seems caused by stale version information of the `gitlab-runner` debian packages.

The repository caches seem not to be updated. When listing all available versions for the package, I only see the old versions:
```
$ sudo apt list -a gitlab-runner
Listing... Done
gitlab-runner/bionic,now 12.10.1 amd64 [installed]
gitlab-runner/bionic 12.10.0 amd64
gitlab-runner/bionic 12.9.0 amd64
# ... older versions omitted for brevity
```

After manually updating the caches on the affected machine, the latest version is available:
```
$ sudo apt update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 https://packages.gitlab.com/runner/gitlab-runner/ubuntu bionic InRelease [23.4 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,023 kB]
# ... other packages omitted for brevity
Get:21 https://packages.gitlab.com/runner/gitlab-runner/ubuntu bionic/main amd64 Packages [10.3 kB]
Fetched 5,185 kB in 3s (1,682 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
74 packages can be upgraded. Run 'apt list --upgradable' to see them.
$ sudo apt list -a gitlab-runner
Listing... Done
gitlab-runner/bionic 13.2.1 amd64 [upgradable from: 12.10.1]
gitlab-runner/bionic 13.2.0 amd64
gitlab-runner/bionic 13.1.1 amd64
gitlab-runner/bionic 13.1.0 amd64
gitlab-runner/bionic 13.0.1 amd64
gitlab-runner/bionic 13.0.0 amd64
gitlab-runner/bionic 12.10.3 amd64
gitlab-runner/bionic 12.10.2 amd64
gitlab-runner/bionic,now 12.10.1 amd64 [installed,upgradable to: 13.2.1]
gitlab-runner/bionic 12.10.0 amd64
gitlab-runner/bionic 12.9.1 amd64
gitlab-runner/bionic 12.9.0 amd64
# ... older versions omitted for brevity
```


After this manual step, the latest version of `gitlab-runner` is correctly installed.

This issue could be resolved by adding [`update_cache`](https://docs.ansible.com/ansible/latest/modules/apt_module.html#parameter-update_cache) to the task installing the package in `tasks/install-debian.yml` (I don't know if there are any undesired side-effects though):

```diff
 - name: (Debian) Install GitLab Runner
   apt:
     name: "{{ gitlab_runner_package }}"
     state: "{{ gitlab_runner_package_state }}"
+    update_cache: yes
   become: true
   environment:
     GITLAB_RUNNER_DISABLE_SKEL: "true"
   when: ansible_distribution_version == "10"
 
 - name: (Debian) Install GitLab Runner
   apt:
     name: "{{ gitlab_runner_package }}"
     state: "{{ gitlab_runner_package_state }}"
+    update_cache: yes
   become: true
   when: ansible_distribution_version != "10"
```

**Comment by riemers** [comment]
There is a PR that does just that, but i think this should not be in this package. If every package maintainer adds a "update cache" then you could end up with updating the cache multiple times which would make it not efficient. Could add a note to the readme that we assume cache is updated?
