### ISSUE TITLE
Help for this repo wanted

### ISSUE THREAD

**Issue by riemers** [riemers/ansible-gitlab-runner#148]
As you might have noticed it is behind a proper repo. If anyone wants to lend a hand to help out that would be great, even if its just to go through some items and fix failing builds etc. Sadly mac and windows are both now complaining and i merged a few things to at least keep up with the requests.

I do check now and then but i don't have the time and resources to check every o.s. and some help would be appreciated (even in the form of PR's but a actual repo maintainer would be nice. Yes, we can share the love in the credits etc etc)

**Comment by maglub** [comment]
I don't mind give a few minutes of my time.

**Comment by riemers** [comment]
I do my best to maintain, merge requests and such but i don't even have gitlab anymore. But i just don't want to throw in the towel like so many projects. Hence why i just do what i can do. Also ansible has native gitlab runner items now so at some point that should be used instead i believe. If you have something i can approve it ofcourse. If you want to maintain it, thats another story :)

**Comment by maglub** [comment]
Ok, I will create a pull request that satisfies my immediate needs in just a bit. This role is much better than the built in ansible module, which requires both a Gitlab API key, and depends on the python-gitlab python module.

**Comment by riemers** [comment]
Thanks, there are still plenty of issues open. If you encounter any of those and you can fix time any help is appreciated.

**Comment by maglub** [comment]
Do you have any other communication channel for discussing the repo? I.e discord, gitter, etc?

**Comment by riemers** [comment]
Not a channel, but if you need me, i'am Riemers#4426 on discord. I am also moving in between houses so i might not respond instantly :)
