### ISSUE TITLE
Switch to gitlab_runner_module for registering runners

### ISSUE THREAD

**Issue by chancez** [riemers/ansible-gitlab-runner#149]
Generally, i see a lot of regex/command module usage in this role and I believe a lot of the logic could be replaced with python in a module. I see the community.general collection has a gitlab_runner_module https://docs.ansible.com/ansible/latest/collections/community/general/gitlab_runner_module.html but it doesn't support everything needed. 

I imagine the module could be updated to handle most of the configuration merging, and runner registration and then replace a good portion of the logic for managing the runner configuration and registration that's done using multiple other tasks/modules today.

**Comment by riemers** [comment]
True, but this has been around for ages. Hence some classic "legacy" i would say. If someone wants to make those changes then i am all for it.
