### ISSUE TITLE
Skip role tasks if runners exist

### ISSUE THREAD

**Issue by ravecat** [riemers/ansible-gitlab-runner#156]
@riemers and team, thank you for nice tool!

Could you clarify, have we unique vars or parameters with that we can skip role if runners already exist.

Current pipeline spends large time, it try to start every time, but runners already installed to system

**Comment by riemers** [comment]
Normally items are idempotent, if that is not the case something would be wrong.

**Comment by quotengrote** [comment]
Same problem here, the runners gets deployed as duplicate every time.
What infos do you need?

**Comment by riemers** [comment]
A big pull request with the issues solved :) like many of the tasks bugs are open but i have no longer time for it. I am still open for PR's so we can still improve so it doesn't die.

**Comment by pnmice** [comment]
Is it possible to register multiple runners on the same machine?
