### ISSUE TITLE
Set clone url step is failing

### ISSUE THREAD

**Issue by lukkigi** [riemers/ansible-gitlab-runner#164]
Hello,

whenever the role tries to set the clone url of a runner, the specific job fails, but the change gets through nevertheless. We have a setup with 18 runners on CentOS 7 machines and every single of them gets the error message below. This causes our ansible playbook to abort after running the gitlab-runner task, which is unfortunate. Could you please look into this?

`TASK [riemers.gitlab-runner : Set clone URL] ***********************************************************************************************************************************************
fatal: [gitlab-runner-xxx]: FAILED! => {"changed": false, "module_stderr": "Shared connection to gitlab-runner-xxx closed.\r\n", "module_stdout": "/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 0}`

The setlocale warning does not seem to be the cause of the problem. When I fix this particular warning, the error still appears, just with an empty stdout message.

Thanks in advance!

**Comment by riemers** [comment]
Just a fyi, i have no clue at the moment. Those set locale issues i have seen before in lots of different situations, i agree i don't think that has anything to do with the issue. Only thought would be that it gives an errorcode back which causes something. (in case of a test, just set a "exit 0" in the end of the lang.sh) just a suggestion for troubleshooting.
