### ISSUE TITLE
Changes to some role variables ignored once runner has been registered

### ISSUE THREAD

**Issue by joelpet** [riemers/ansible-gitlab-runner#17]
**Steps to reproduce:**

1. Start from a clean slate (e.g. by running `gitlab-runner unregister --all-runners`)
2. Set a variable used in runner registration, e.g. `gitlab_runner_docker_volumes: ['/cache']`
3. Run role
4. Change to `gitlab_runner_docker_volumes: ['/tmp']`
5. Run role again

**Expected:**
`/etc/gitlab-runner/config.toml` contains a single runner with a `[runners.docker]` entry `volumes = ["/tmp"]`

**Actual:**
`/etc/gitlab-runner/config.toml` contains a single runner with a `[runners.docker]` entry `volumes = ["/cache"]`

**Discussion:**
Runner registration is skipped as soon as a runner is found among the registered runners that matches the description of the runner for which the `gitlab_runner_docker_volumes` variable was updated. Ideally, registration should be re-run whenever dependent role variables change.

**Comment by riemers** [comment]
Agreed, if you can create a pull request that would be nice. I can imagine this would take more time then a normal "typo" or loop to fix. I will leave this ticket open for that matter in case you or me or anyone else finds the time to make this proper.

**Comment by paulRbr** [comment]
I am currently working on getting a PR for this. It's pretty anoying to not be able to modify an already registered runner.
