### ISSUE TITLE
Error: Version 'XX.XX.XX' for 'gitlab-runner' was not found

### ISSUE THREAD

**Issue by nop33** [riemers/ansible-gitlab-runner#178]
Unless I add `update_cache: yes` in the task `(Debian) Install GitLab Runner` of the `ansible-galaxy/roles/gitlab-runner/tasks/install-debian.yml` file, I am getting the above error.

**Comment by riemers** [comment]
If your system is out of date and it needs to update the cache which is part of your o.s. that is not something that should be part of this role though. Unless your referring to something else.

**Comment by karolisc** [comment]
related https://github.com/riemers/ansible-gitlab-runner/pull/186
