### ISSUE TITLE
Literal `>` becomes part of executed command

### ISSUE THREAD

**Issue by joelpet** [riemers/ansible-gitlab-runner#18]
https://github.com/riemers/ansible-gitlab-runner/blob/77391854ce73ff2fe0bd20dbfbb9d5d27cc42f8e/tasks/register-runner.yml#L9

This seems to be a mistake as a literal `>` character shows up as part of the command being run on the host. I checked by adding `-vv` to the `ansible-playbook` command.

The following, however, works as I would have expected it to:

```
- name: Register runner to GitLab
  command: >-
    gitlab-runner register
    --non-interactive
...
```

**Comment by riemers** [comment]
The > is used because ansible uses YAML syntax. It indicates that the next lines needs to be 'joined'  see https://yaml-multiline.info/ for example (one of the first hits i found) but i can imagine the confusion (i had that too at the start)

**Comment by joelpet** [comment]
When using a YAML block scalar format, the block scalar header (consisting of style, chomping, and indentation indicator) must follow immediately after the property name, e.g.:

```
  command: >-
    gitlab-runner register
    --non-interactive
```

If it's not at the very beginning of the string, the string will be interpreted as a flow scalar, in this case, resulting in the following:

```
TASK [riemers.gitlab-runner : Register runner to GitLab] ************************************************************************************
task path: .../riemers.gitlab-runner/tasks/register-runner.yml:8
changed: [<redacted>] => {"changed": true, "cmd": ["gitlab-runner", "register", ">", "--non-interactive", "--url", "https://gitlab.com/ci", "--registration-token", "<redacted>", "--description", "AWS runner", "--tag-list", "", "--executor", "docker", "--limit", "0", "--locked=false", "--docker-image", "ubuntu:16.04", "--docker-volumes", "/cache", "/etc/ssh/known_hosts:/etc/ssh/known_hosts", "--ssh-user", "", "--ssh-host", "", "--ssh-port", "", "--ssh-password", "", "--ssh-identity-file", ""], ...}
```

Notice how a literal `>` is part of the command.

**Comment by riemers** [comment]
I see what you mean now, i get it my bad.
