### ISSUE TITLE
Only first Docker volume added to runner configuration

### ISSUE THREAD

**Issue by joelpet** [riemers/ansible-gitlab-runner#19]
The following vars definition

```
gitlab_runner_docker_volumes:                  
  - "/cache"                                   
  - "/tmp"
```
results in a registration command like this:

```
gitlab-runner register ... --docker-volumes "/cache" "/tmp" ...
```

which does not seem to have the expected result—i.e. only `/cache` is being added as a volume in `/etc/gitlab-runner/config.toml` instead of both `/cache` and `/tmp`.

With the following code in place at https://github.com/riemers/ansible-gitlab-runner/blob/77391854ce73ff2fe0bd20dbfbb9d5d27cc42f8e/tasks/register-runner.yml#L19 it works as expected (both volumes show up in `config.toml`):

```
    {% for volume in gitlab_runner_docker_volumes | default([]) %}
    --docker-volumes "{{ volume }}"
    {% endfor %}
```

---

```
$ gitlab-runner --version
Version:      11.1.0
Git revision: 081978aa
Git branch:   
GO version:   go1.8.7
Built:        2018-07-22T07:24:46+00:00
OS/Arch:      linux/amd64
```

**Comment by riemers** [comment]
Can you make a pull request for this?
