### ISSUE TITLE
Duplicate runners section in config.toml on Windows

### ISSUE THREAD

**Issue by deephack1982** [riemers/ansible-gitlab-runner#194]
Hello!

I have a playbook which looks something like this
`---
- name: Windows machines
  hosts: windows-pool
  vars_files:
    - '../secrets.yml'
  roles:
    - riemers.gitlab-runner
  vars:
    gitlab_runner_runners:
    - name: "{{ inventory_hostname }}"
      token: "{{ gitlab_runner_token }}"
      url: "{{ gitlab_url }}"
      executor: shell
      tags:
      - azure
      - windows
      - ta `

When I apply it I get an error that the verify config task fails. When I look at the resulting config.toml file on the host it has a duplicated runners section like this

`[[runners]]
[[runners]]`

Am I doing something wrong or is this a bug? Same playbook applies perfectly on an Ubuntu machine.

**Comment by oscillate123** [comment]
This is an issue for us as well. I think the issue is within `/riemers.gitlab-runner/tasks/update-config-runner-windows.yml`

```
ansible [core 2.11.6] 
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

riemers/ansible-gitlab-runner version: 4cba5bb5e4e2a61adbd684e318370ff4714401ed (master from 2021-12-03)

**Comment by oscillate123** [comment]
I have solved this issue and planning on making a PR to this repository.
@deephack1982 
@riemers
