### ISSUE TITLE
Bind mount path is hard coded

### ISSUE THREAD

**Issue by obvionaoe** [riemers/ansible-gitlab-runner#198]
Hi, I think the bind mount path for the Docker Container should not be hard coded to start to /srv/* like in the example below.
There are several files where this happens and I think it'd be better to have it as a default but not make it obligatory, as the users should be able to specify their desired path!

https://github.com/riemers/ansible-gitlab-runner/blob/5caa92463e00a8b9ed9fe0f94d2d56230fd4a79b/tasks/install-container.yml#L10

Anyways, thanks for the great work!

**Comment by riemers** [comment]
Your totally correct, but lack of time. So a PR is the only option for now
