### ISSUE TITLE
No override variable for url

### ISSUE THREAD

**Issue by obvionaoe** [riemers/ansible-gitlab-runner#199]
Hey, I believe the line referenced below should be 
```yaml
--url '{{ gitlab_runner.url|default(gitlab_runner_coordinator_url) }}'
```
instead, otherwise the url passed under gitlab_runner_runners for each runner will not override the gitlab_runner_coordinator_url.

https://github.com/riemers/ansible-gitlab-runner/blob/d13e4e11366457e4a74986c429c1fba0c681efed/tasks/register-runner-container.yml#L24

Thanks

**Comment by riemers** [comment]
Sounds logic, same remark as the last issue applies.
