### ISSUE TITLE
Debian 11 (bullseye) support

### ISSUE THREAD

**Issue by nickbroon** [riemers/ansible-gitlab-runner#210]
Currently there is on GitLab Runner package published for Debian Bullsye:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27935

Though the repo setup script will run, it will then fail to find package.

Using the 'buster' /etc/apt/sources.list.d/ entry seems to work for the moment.

So perhaps the role could detect that it's deploying on bullseye and modify the /etc/apt/sources.list.d/ created by the installer to reference buster instead?

**Comment by marcelbrueckner** [comment]
The referenced issue was fixed by GitLab just a few weeks ago. I installed GitLab Runner 14.8.2 via this role on Debian Bullseye just fine and my `/etc/apt/sources.list.d/runner_gitlab-runner.list` reads like so:

```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/runner/gitlab-runner

deb https://packages.gitlab.com/runner/gitlab-runner/debian/ bullseye main
deb-src https://packages.gitlab.com/runner/gitlab-runner/debian/ bullseye main
```
