### ISSUE TITLE
Privileged mode requires a second run

### ISSUE THREAD

**Issue by joelpet** [riemers/ansible-gitlab-runner#22]
**Steps to reproduce:**
1. Set `gitlab_runner_docker_privileged: true`
2. Run provisioning
3. Check `/etc/gitlab-runner/config.toml` on host
4. Run provisioning again
5. Check `/etc/gitlab-runner/config.toml` on host again

**Expected:**
- Step 3: `privileged` is `true`
- Step 5: `privileged` is `true`

**Actual:**
- Step 3: `privileged` is `false`
- Step 5: `privileged` is `true`

**Comment by riemers** [comment]
Have not noticed that before, might be good to combine fixing of things like this with the rerun of new config values for the config.toml

p.s. concerning your other 2 merge request those are merged, if you have more then i can combine those all to make a release. Let me know if you need a new release since it will push it to galaxy then.

**Comment by joelpet** [comment]
The problem here is that the `privileged` property is set in `global-setup.yml`, which is run before `register-runner.yml`, so on the first run the value of `privileged` comes from `register-runner.yml`, and on the second run `register-runner.yml` is not run because there is already a runner registered so it leaves the value that `global-setup.yml` set.

The solution to this particular issue is simply including the `--docker-privileged` flag in the runner registration command. I'll create a pull request for this in a minute.

If we find a good way to rerun registration we should be able to get rid of the `global-setup.yml` and instead rely on command line options to `gitlab-runner register`.

Re:ansible-galaxy Thank you, that would be most appreciated.

**Comment by riemers** [comment]
pushed to galaxy
