### ISSUE TITLE
MacOS remote installation

### ISSUE THREAD

**Issue by jeremad** [riemers/ansible-gitlab-runner#237]
According to the [gitlab documentation](https://docs.gitlab.com/runner/install/osx.html#limitations-on-macos) :
> The service needs to be installed from a Terminal window logged in as your current user. Only then will you be able to manage the service.
> To sign in as your current user, run the command `su - <username>` in the terminal. You can obtain your username by running the command `ls /users`.

I tried multiple things, playing around, but I think this makes it impossible to start the gitlab runner via ansible on a remote host.
I get the following error on the "(MacOS) Start GitLab Runner" step
```
FATAL: Failed to start gitlab-runner: "launchctl" failed with stderr: Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
```
It used to work fine with gitlab-runner < 14.0, but now this makes this role ususable on MacOS (unless locally).

I think adding a variable to try no to start the runner, and starting it manually later on would do the trick for me. I'll make a PR so you tell me what you think.

Cheers.

**Comment by riemers** [comment]
On vacation right now. I’ll check the pr’s next week ;)
________________________________
Van: Jeremy Tellaa ***@***.***>
Verzonden: Tuesday, April 26, 2022 12:10:02 PM
Aan: riemers/ansible-gitlab-runner ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [riemers/ansible-gitlab-runner] MacOS remote installation (Issue #237)


According to the gitlab documentation<https://docs.gitlab.com/runner/install/osx.html#limitations-on-macos> :

The service needs to be installed from a Terminal window logged in as your current user. Only then will you be able to manage the service.
To sign in as your current user, run the command su - <username> in the terminal. You can obtain your username by running the command ls /users.

I tried multiple things, playing around, but I think this makes it impossible to start the gitlab runner via ansible on a remote host.
I get the following error on the "(MacOS) Start GitLab Runner" step

FATAL: Failed to start gitlab-runner: "launchctl" failed with stderr: Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.


It used to work fine with gitlab-runner < 14.0, but now this makes this role ususable on MacOS (unless locally).

I think adding a variable to try no to start the runner, and starting it manually later on would do the trick for me. I'll make a PR so you tell me what you think.

Cheers.
