### ISSUE TITLE
Gitlab option pre_clone_script is deprecated

### ISSUE THREAD

**Issue by dot-mike** [riemers/ansible-gitlab-runner#255]
The option `pre_clone_script` is deprecated in favor of `pre_get_sources_script`

Ref: https://docs.gitlab.com/ee/update/deprecations.html#deprecation-and-planned-removal-for-ci_pre_clone_script-variable-on-gitlab-saas
Deprecation and planned removal for CI_PRE_CLONE_SCRIPT variable on GitLab SaaS.
End of Support: GitLab 15.11 (2023-04-22)
Planned removal: GitLab 15.11 (2023-04-22)

**Comment by riemers** [comment]
This was mentioned for CI_PRE_CLONE_SCRIPT not PRE_CLONE_SCRIPT btw ;) re-open if i am wrong..

**Comment by riemers** [comment]
My bad, looks like it needs an update indeed, anyone willing to do a search & replace? :)
