### ISSUE TITLE
restart_gitlab_runner_windows handler running on some Ubuntu server hosts

### ISSUE THREAD

**Issue by ctorgalson** [riemers/ansible-gitlab-runner#258]
I haven't managed to debug how this can happen, but I'm consistently seeing this on a host (note `gitlab_runner_container_install` is explicitly set to `false` and the playbook containing the role _does_ work on about two dozen other hosts):

![image](https://user-images.githubusercontent.com/1063424/231709726-b7f08514-2302-464c-a4b8-31986233bfd9.png)

Inserting some debug code shows that:

- the [right variables file](https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/main.yml#L3-L11) is included
- only [the Unix condition in the main playbook](https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/main.yml#L19) is true
- only [the non macOS condition in the handlers file](https://github.com/riemers/ansible-gitlab-runner/blob/master/handlers/main.yml#L6) is true
- `ansible_os_family` correctly evaluates to `Debian`
- `ansible_distribution` correctly evaluates to `Ubuntu`

I'm a bit confused. It's tricky to step through the role, but I'll be taking another look next week.

**Comment by riemers** [comment]
See your busy bee, windows does not always get the love it needs too. So any help is appreciated.
