### ISSUE TITLE
Refresh update cache prior to running repository installation script

### ISSUE THREAD

**Issue by benjamb** [riemers/ansible-gitlab-runner#259]
This may only be relevant to Debian, more specifically an issue when using fresh vagrant boxes. However  when testing the role as documented in the README, i.e. with a simple playbook with:

```
- hosts: all
  become: true
  roles:
    - role: riemers.gitlab-runner
```

The installation fails with the following message:

```
Package curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'curl' has no installation candidate
Unable to install curl! Your base system has a problem; please check your default OS's package repositories because curl should work.
Repository installation aborted.
```

This is resolved with a simple call to refresh the package cache.

**Comment by riemers** [comment]
just a fyi, in the past people wanted something similar but was always against it since it would always run. The cache is a good addition for this not to run constantly. Although i still think it should belong to a bigger playbook it is less intrusive now.
