### ISSUE TITLE
Ansible galaxy releases

### ISSUE THREAD

**Issue by achaussier** [riemers/ansible-gitlab-runner#26]
Hello,

Thanks for this role. Please, can you import to galaxy the latest releases because the last on Galaxy is v1.1.5.

Have a nice day

**Comment by riemers** [comment]
Thats weird, whenever i make a release it used to go automatic. For some reason it stopped doing that. Imported manually from ansible galaxy, i'll keep an eye out if there is a new version if it happens again.

**Comment by achaussier** [comment]
Thanks
