### ISSUE TITLE
Custom build dir extra variable not working

### ISSUE THREAD

**Issue by orihomie** [riemers/ansible-gitlab-runner#262]
Hello! I'm trying to set up runner with specific [custom build directory](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnerscustom_build_dir-section). 
```
          extra_configs:
            runners.custom_build_dir:
              enabled: "true"
```

And it's not working.
I've tried to apply all samples with `extra_configs` and they seem not working too.

**Comment by riemers** [comment]
Check to see if its supported in the code, if not add it. (assuming it is just as easy as adding a new option to it)
