### ISSUE TITLE
New runner register system.

### ISSUE THREAD

**Issue by animalillo** [riemers/ansible-gitlab-runner#269]
Gitlab has changed the expected runner registration and it must now be initialized from the web UI.

I am trying to set up a runner using ansible and this module, but i get the following error: ` Runner configuration other than name and executor configuration is reserved and cannot be specified when registering with a runner token. This configuration is specified on the GitLab server. Please try again without specifying those arguments.`

**Comment by riemers** [comment]
Would be weird if they changed it so you can only register via the web ui?

**Comment by guenhter** [comment]
I looked into this yesterday, and it seems with Gitlab 16.x the registration token is deprecated. Instead of that, you have to go to the Gitlab UI, tell Gitlab that you want to have a new runner with a certain tags. Then Gitlab generates an authorization token for this particular runner and this token is then used in the registration command for that single runner. 
I don't know why Gitlab changed their way, but having the UI involved just for the sake of adding a new runner seems like a step back to me ... but maybe I'm missing something...

**Comment by riemers** [comment]
That just sounds like the role as it stands, will have no purpose..

**Comment by guenhter** [comment]
I mean this role still can do what is does after the registration happened by configure stuff in the `config.toml`. The registration of the runner itself on the other hand is not longer possible then (but maybe I missed something in the new gitlab way or misinterpreted it).

**Comment by riemers** [comment]
Lets assume they are not making it less smart :)

**Comment by animalillo** [comment]
It seems that you can get an old fashioned token, which is what i used for this setup, but there was a document where they explained the reasoning behind doing it this way instead of the old way.

I think this module still fits it's place, just some little tweaks needed to support the new way. With host variables it can easily be sorted out and you have unike tokens for each runner.

**Comment by guenhter** [comment]
@animalillo Maybe you could share your thoughts on this what would be needed to support the new way.

**Comment by guenhter** [comment]
Today I stumbled across this Release Notes post:

https://about.gitlab.com/releases/2023/05/22/gitlab-16-0-released/#rest-api-endpoint-to-create-a-runner

It says that there is a REST endpoint to create a new Runner in Gitlab and get the access token for it.
With that endpoint, it should be then easy to dynamically create runners as we want it with the new authentication token system, without the need for the deprecated registration token.
