### ISSUE TITLE
Decouple scripts from the registration command to prevent execution errors

### ISSUE THREAD

**Issue by rlisewski** [riemers/ansible-gitlab-runner#270]
I encountered an issue with the `pre_build_script` during the runner registration process. When a script is included in the `pre_build_script` variable, it results in malformed JSON in the registration command. For example:

```yaml
gitlab_runner_runners:
  - name: "{{ runner_name }}"
    pre_build_script:
      if which docker >/dev/null; then
        echo Login to docker;
        docker login -u <user_name> -p "$(cat <file_name>)";
      fi;
```
This configuration leads to broken JSON:
```json
    "--pre-build-script",
    "if which docker >/dev/null; then echo Login to docker;docker login -u <user_name> -p $(cat",
    " <file_name>); fi;",
```
The issue arises because scripts are included in the registration command without proper handling or escaping. Scripts are not actually required during runner registration. They are updated later on during playbook execution.

I propose to decouple scripts from the registration command to prevent such execution errors. This change would ensure the robustness of the registration process and avoid unnecessary complications.

**Comment by riemers** [comment]
Think this can be closed ;)
