### ISSUE TITLE
Support of gitlab 15.6+ runners registration way.

### ISSUE THREAD

**Issue by ykslol** [riemers/ansible-gitlab-runner#288]
Not an issue, more a feature request
Runner registration via registration token was deprecated In GitLab 15.6 and planned for removal in Gitlab 17.0.
In new way we need to register a runner created in the UI with an authentication token.

Is it planned to add support of new runner registration workflow? 
May be someone started to work on it?

Suppose it should be a request to Gitlab  API for creation a runner with catching an auth token and then registration it with replacement of `--registration-token` to `--token`.

[ API For runner creation](https://docs.gitlab.com/ee/api/users.html#create-a-runner)
Curl example of group-runner creation via API:
```
curl --silent --request POST --url "https://gitlab.example.com/api/v4/user/runners"
  --data "runner_type=group_type"
  --data "group_id=<group_id>"
  --data "description=<your_runner_description>"
  --data "tag_list=<your_comma_separated_job_tags>"
  --header "PRIVATE-TOKEN: <group_access_token>"
  ```

**Comment by guenhter** [comment]
Duplicate of https://github.com/riemers/ansible-gitlab-runner/issues/269

**Comment by osksa** [comment]
> Duplicate of #269

Yes, but that issues is closed. I also want the feature @ykslol proposes, so I think it would be nice to have an open issue on it? (Or reopen #269 )

**Comment by ykslol** [comment]
@osksa i think it is no matter which task should be opened.
I think i could to post all info, which i posted here, in old task, when it be reopened. And then we could continue our discussion there.

Offtopic - may be required other issue started
Today i registered runner by hands via binary. In new version of this role i think we need to make deprecation for repo installation. This features were added in installation via binary:
From gitlab-docs:
# Download the binary for your system
sudo curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64

# Give it permission to execute
sudo chmod +x /usr/local/bin/gitlab-runner

# Create a GitLab Runner user
sudo useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash

# Install and run as a service
sudo gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
sudo gitlab-runner start

Really simple -  no repo installation any more. 
Just download, install via builtin runner command and register it with parameters which u need.

With new workflow of gitlab registration - runners management will be much more easy.

**Comment by Grokzen** [comment]
I would like to add a +1 for this needs to be supported sooner rather then later. Gitlab 17.0 is slated to be released on 2024-05-16 according to their own page here https://about.gitlab.com/upcoming-releases/

It would also be to assume that 17.0 would roll out on the SaaS site gitlab.com soon after that and then this feature would stop working in this ansible module and ppl who register runners with this module probably would have to revert back to something that @ykslol mentions in previous comments and just run that set of code as a bash script or something

**Comment by guenhter** [comment]
In our company we have this on our Radar and want to implement this in the next weeks

**Comment by riemers** [comment]
Then its just 'company work' right? 😎

**Comment by guenhter** [comment]
:)

**Comment by riemers** [comment]
maybe need to change those bot things a bit..

**Comment by gardar** [comment]
Rather than using curl, how about using the [community.general.gitlab_runner](https://docs.ansible.com/ansible/latest/collections/community/general/gitlab_runner_module.html) module? It can be used for registering the runner using both the old and new registration methods and it returns a token which can be written to the runner config.

**Comment by guenhter** [comment]
This is a great idea!
