### ISSUE TITLE
Support for AlmaLinux

### ISSUE THREAD

**Issue by Leny1996** [riemers/ansible-gitlab-runner#291]
Hello,
we're trying to deploy gitlab-runner on AlmaLinux servers and we encountered an error regarding pygpgme package.
Looks like it could be easily fixed by adding the same for AlmaLinux inside `install-redhat.yml`:
```
- name: (RedHat) Install Gitlab repository
  command: >
    {% if ansible_distribution == "Rocky" %}
    env os=el dist={{ ansible_distribution_major_version }}
    {% endif %}
    bash /tmp/gitlab-runner.script.rpm.sh
 ```

**Comment by guenhter** [comment]
Hi, feel free to open a PR for this. I'm happy to review this then.
