### ISSUE TITLE
How to set custom_build_dir_enabled as variable

### ISSUE THREAD

**Issue by dosas** [riemers/ansible-gitlab-runner#298]
I am trying to enable the custom build dir for gitlab-runner: https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnerscustom_build_dir-section

I have found the [check](https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/register-runner.yml#L132) for `custom_build_dir_enabled` but this variable is not present in [defaults/main.yml](https://github.com/riemers/ansible-gitlab-runner/blob/master/defaults/main.yml)

How can I set this variable?

**Comment by riemers** [comment]
Just because the variable is not in the main.yml doesn't mean you cannot use it. The defaults/main.yml is an example after all, and sometimes people create a new option but not always add this in the main.yml of the defaults.
