### ISSUE TITLE
Error when upgrading from gitlab-runner version 15.0.0 to 16.6.0

### ISSUE THREAD

**Issue by mlevieux** [riemers/ansible-gitlab-runner#299]
Hi,

I'm trying to upgrade the `gitlab-runner` version we're using on our different machines.
The version prior to the upgrade is `15.0.0`, and I'm upgrading to `16.6.0`.

Everything went fine with Linux and Windows machines, but on MacOS, the `gitlab-runner` executable returns weird errors at the following step:
```
TASK [gitlab_runner_install_and_register : (MacOS) Stop GitLab Runner] *********************************************************************************************************************************************************
fatal: [*** MACHINE ***]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/gitlab-runner", "stop"], "delta": "0:00:00.024570", "end": "2023-11-23 13:48:19.054515", "msg": "non-zero return code", "rc": 1, "start": "2023-11-23 13:48:19.029945", "stderr": "Runtime platform                                  \u001b[0;m  arch\u001b[0;m=amd64 os\u001b[0;m=darwin pid\u001b[0;m=72729 revision\u001b[0;m=febb2a09 version\u001b[0;m=15.0.0\n\u001b[31;1mFATAL: Failed to stop gitlab-runner: exit status 1\u001b[0;m ", "stderr_lines": ["Runtime platform                                  \u001b[0;m  arch\u001b[0;m=amd64 os\u001b[0;m=darwin pid\u001b[0;m=72729 revision\u001b[0;m=febb2a09 version\u001b[0;m=15.0.0", "\u001b[31;1mFATAL: Failed to stop gitlab-runner: exit status 1\u001b[0;m "], "stdout": "", "stdout_lines": []}
```

which is very weird. It seems the executable is found and works but the process cannot be stopped for whatever reason.

Additionally, when on the instance itself, as the same user, I run (order is important):
```
$ gitlab-runner stop
$ gitlab-runner status
```
I get a strange error saying: `\"launchctl\" failed with stderr: Could not find service \"gitlab-runner\" in domain for port`. Is that related?

Have you ever encountered this issue? Does it come from a new version of `gitlab-runner` requiring additional configuration ? The playbook runs well when the version does not change.

Thank you

**Comment by mlevieux** [comment]
Note that only `gitlab-runner start` and `gitlab-runner stop` seem to be an issue here. In particular, if I comment out the `(MacOS) Stop GitLab Runner` task, then the `(MacOS) Start GitLab Runner` task errors with:
```
"stderr_lines": [
        "Runtime platform                                  \u001b[0;m  arch\u001b[0;m=amd64 os\u001b[0;m=darwin pid\u001b[0;m=90564 revision\u001b[0;m=3046fee8 version\u001b[0;m=16.6.0",
        "\u001b[31;1mFATAL: Failed to start gitlab-runner: \"launchctl\" failed with stderr: Load failed: 5: Input/output error",
        "Try running `launchctl bootstrap` as root for richer errors.",
        "\u001b[0;m "
    ]
```
but still upgrades the runner.

**Comment by riemers** [comment]
Input/output error, that is indeed weird. From my experience if i see this it is usually because it is a mounted filesystem or share which is broken on where it is trying to do its work. Doing some catchups, so if the problem still exist reopen if needed.
