### ISSUE TITLE
Debian Unhold: Failed to find package from ansible-core >=2.16

### ISSUE THREAD

**Issue by wknd** [riemers/ansible-gitlab-runner#301]
The role fails to install on Debian/Ubuntu when using ansible-core >=2.16 on the ```(Debian) Unhold GitLab Runner version``` task.  
It will not fail if gitlab-runner is already installed previously.

```
...
TASK [riemers.gitlab-runner : (Debian) Set gitlab_runner_package_name] ******************************************************************************************************
ok: [10.20.1.55]

TASK [riemers.gitlab-runner : (Debian) Unhold GitLab Runner version] ********************************************************************************************************
fatal: [10.20.1.55]: FAILED! => {"changed": false, "msg": "Failed to find package 'gitlab-runner' to perform selection 'install'."}
```

It worked previously when I was at work, but not anymore when I'm at home. I traced it to [this change](https://github.com/ansible/ansible/commit/f10d11bcdc54c9b7edc0111eb38c59a88e396d0a)  in behavior of dpkg_selections https://github.com/ansible/ansible/issues/81404 .  
```dpkg_selections``` will from now on fail if the package isn't installed already.

The simple solution seems to be to place the ```Unhold``` task after the ```Install``` task.  
But I'm not sure if that would create some unintended consequences. If it was previously set to hold, and then you install again, would it install the newly specified version or the one that was hold?

Otherwise I guess using ansible_facts or something to check if the package was installed before using ```dpkg_selections```.

**Comment by sergeeximius** [comment]
I just got the same problem on Debain 12 (bookworm). It helped to execute this command manually on a remote server:
```
sudo apt-cache dumpavail | sudo dpkg --merge-avail
echo gitlab-runner install | sudo dpkg --set-selections
```
