### ISSUE TITLE
Galaxy role renamed back from ansible-gitlab-runner to gitlab-runner

### ISSUE THREAD

**Issue by dominik-horb-umg** [riemers/ansible-gitlab-runner#305]
It looks like on January 9th 2024 the Galaxy role was renamed back from `ansible-gitlab-runner` to `gitlab-runner` by a developer from Ansible Galaxy:

https://forum.ansible.com/t/lost-all-history-of-ansible-role-after-delete-of-a-another-role/1753/5

As this seems to be a somewhat surprising change, it seemed sensible to open an issue here if only to change the README if nothing else and in case someone else stumbles upon this problem.

The simple fix for us was to change the name in our `requirements.yml` and the role usage.

**Comment by guenhter** [comment]
![](https://media.giphy.com/media/3o7527pa7qs9kCG78A/giphy.gif)

**Comment by riemers** [comment]
Made it to the finish ;p

![image](https://github.com/riemers/ansible-gitlab-runner/assets/682041/6985b303-aaf4-476f-afe2-e78128b3119a)

Thanks for the heads up, i'll remove the note. We need to do some action now again. For one automated imports needs to be fixed to match the repo again.

**Comment by riemers** [comment]
Seems travis is out of credits, i'll mail them for open source too. Also need to figure out the auto imports into galaxy from new version.  @guenhter , maybe we should have a chat or something so we can make this reflect / get back in shape if thats ok with you?

**Comment by guenhter** [comment]
Hi, currently I'm not very active because I'm snowed under with work...

**Comment by riemers** [comment]
Yeah you and me both , have a workshop for 24+ ppl tomorrow.. but we will make do with what we can.

**Comment by guenhter** [comment]
Yes, I try to invest time where it is important in this repo and ignore nice-to-haves for now.

**Comment by riemers** [comment]
Already happy with all the work you done so far too.

**Comment by guenhter** [comment]
> maybe we should have a chat or something so we can make this reflect / get back in shape if thats ok with you?

@riemers what plans do you have?
