### ISSUE TITLE
New registration workflow

### ISSUE THREAD

**Issue by mathieu-pousse** [riemers/ansible-gitlab-runner#331]
Hi there, 

I'm wondering how to register a runner with the new Gitlab registration workflow for the runners with authentication token instead of registration token 

https://docs.gitlab.com/runner/register/#register-with-a-runner-authentication-token

Is there any mean to achieve this with this role ?

Note: I've tried to create the runner with this role, without the registration code, and use the community plugin (https://docs.ansible.com/ansible/latest/collections/community/general/gitlab_runner_module.html) to register the freshly created runner without success :disappointed: 

Thanks in advance

**Comment by guenhter** [comment]
https://github.com/riemers/ansible-gitlab-runner/issues/288

**Comment by mateuszkwiatkowski** [comment]
Can you re-open this. Old workflow is going to be removed in Gitlab 18: https://docs.gitlab.com/ee/ci/runners/new_creation_workflow.html

**Comment by artybdrlt** [comment]
If I do understand the new registration process correctly, you can either obtain the registration token through the UI or through Gitlab API. 
Similar to what the [community.general.gitlab_runner Ansible module has implemented](https://docs.ansible.com/ansible/latest/collections/community/general/gitlab_runner_module.html) we could develop a new task that would call the Gitlab API, get the token and use it to carry on the registration process through the role.

Does it make sense?

**Comment by cchaudier** [comment]
I can look this for Linux runners.

**Comment by riemers** [comment]
Isn't then https://github.com/riemers/ansible-gitlab-runner/pull/337?notification_referrer_id=NT_kwDOAApoObIxMTM4Mjg4MzIwMDo2ODIwNDE the same?
