### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Triqueon** [riemers/ansible-gitlab-runner#332]
Would it be possible to get a new release?

As far as I can tell, the version that ansible-galaxy installs is from last October, and appears to be broken for debian due to a missing condition on the Unhold Gitlab Runner version task. This is already fixed in this repository, but not yet present in upstream.

**Comment by pad92** [comment]
Hello,

I have this issue with v2.0.3 on fresh install of ubuntu 22.04.4 LTS

**Comment by Triqueon** [comment]
Workaround: go to wherever the relevant machine stores galaxy roles (Default  ~/.ansible/roles), clear out the riemers.gitlab-runner folder and clone this repo to that spot. That's neither nice nor a long-term solution, but will work for now.

**Comment by riemers** [comment]
Sorry about that, i'll see what i can do. I don't know if @guenhter can also do this. If not i'll explain it. Since last time it went all poof and it took a long time to get something restored.

**Comment by guenhter** [comment]
I don't think I can create new releases because I don't have permissions to create tags or releases

**Comment by riemers** [comment]
![image](https://github.com/riemers/ansible-gitlab-runner/assets/682041/a42da82b-fd02-4bbd-98cb-826a92ea2cce)

**Comment by riemers** [comment]
@guenhter , i don't see an option to add you for tags. But even so it would require you to also allow imports on galaxy (unless that goes automatic, which it normally should though) funny i changed jobs. I am actually now back at the place where i started with this role and they have moved away from gitlab. The irony is high.

**Comment by guenhter** [comment]
:)

**Comment by Curtisjk** [comment]
Will this new release be added to Ansible Galaxy? It is still showing the old 2.0.3 version as latest.

**Comment by riemers** [comment]
https://galaxy.ansible.com/ui/standalone/roles/riemers/ansible-gitlab-runner/versions/ i see 2.4 there..

**Comment by Curtisjk** [comment]
Apologies, I was still using the old `riemers.gitlab-runner` repo. I can see it now :)
