### ISSUE TITLE
Add an option not to overwrite existing runner config

### ISSUE THREAD

**Issue by avolkov** [riemers/ansible-gitlab-runner#37]
I've been using your playbook to install gitlab runner.

My configuration is that the ansible playbook I use is ran against a persistent machine, and not a docker image.
Whenever I make the changes to the playbook, that includes runner config and re-run it, the role ignores existing runner configuration and overwrites it with the new runner config, as  a result the old runner stops reporting and I need to re-enter all project-specific settings for that runner in gitlab.

Would it be possible and reasonable to add an option that would make this playbook skip re-registering runner if the runner is already installed and configured on the system? I.e. if config file in /etc/gitlab-runner/config.toml exists, skip registering the runner if skip registration option is enabled.

**Comment by riemers** [comment]
I think you want https://github.com/riemers/ansible-gitlab-runner/pull/34 right? :)

**Comment by avolkov** [comment]
@riemers Yes! This is the last point of the PR. Sorry I should have read it more carefully.
