### ISSUE TITLE
gitlab runner repo installation is not idempotent

### ISSUE THREAD

**Issue by mwasilew2** [riemers/ansible-gitlab-runner#5]
repo installation script should only run if the repo is missing

this can be achieved in a few ways:
	1. Ansible should provide a fact about configured package repositories, run the script conditionally on that fact
	2. gather the relevant fact inside this module
	3. install repo using Ansible's apt_repository + handle anything else that is in that script

ad 1
such fact doesn't exist at the moment, it's handled by internal logic of apt_repository: https://github.com/ansible/ansible/blob/adc8d607643c3406b88ea9a3b4a9a537f02aa991/lib/ansible/modules/packaging/os/apt_repository.py#L352

ad 2
Probably the quickest and easiest, options:
- local facts (using /etc/ansible/facts.d on remote machines)
- fact gathering task using AnsibleModule: https://github.com/ansible/ansible/blob/5b109506c4a4d1ecfdc9d77184ed1175f4275c95/lib/ansible/module_utils/basic.py#L2111
- capture output of command: https://stackoverflow.com/a/34487201

ad 3
Not really a fan of this approach, the install script/dependencies will evolve in time, so this will introduce constant maintenance overhead. Besides, it feels like redoing somebody else's job.

**Comment by riemers** [comment]
More then happy to merge a PR request for this.

**Comment by mwasilew2** [comment]
I'll go with local facts then, an executable shell script that will check state of the system and will return a simple json with a fact

**Comment by riemers** [comment]
As long as the local facts can be used by everyone that is using this. Used to be different, but we can assume most people moved on by now i suppose.

**Comment by riemers** [comment]
Merged another PR, feel free to make one if you still need some changes, closing for now.

**Comment by earboxer** [comment]
I think this is still a problem. One of my jobs failed when I was applying ansible.

> TASK [riemers.gitlab-runner : (Debian) Install GitLab Runner] ******************
> changed: [servername]

It was while this task was being applied that my job hung. Ansible finished applying, but my job never finished.

(This updated my gitlab-runner from `12.3.0 (a8a019e0)` to `12.4.1 (05161b14)`)

**Comment by riemers** [comment]
Unless someone wants to dig into this, i don't see it a change quickly. Does not happen that much too people it seems. But your always welcome to think of a PR
