### ISSUE TITLE
fix typo in tasks/global-setup.yml

### ISSUE THREAD

**Issue by besmirzanaj** [riemers/ansible-gitlab-runner#53]
file has extra line in the EOF with a single "-" character. this fails ansible-lint as it does not like the empty task

    16:55 $ cat roles/riemers.gitlab-runner/tasks/global-setup.yml
    ---
    - name: Set concurrent option
      lineinfile:
        dest: /etc/gitlab-runner/config.toml
       regexp: '^(\s*)concurrent ='
        line: '\1concurrent = {{ gitlab_runner_concurrent }}'
        state: present
        backrefs: yes
      notify: restart_gitlab_runner
    
    - name: Add sentry dsn to config
      lineinfile:
        dest: /etc/gitlab-runner/config.toml
        regexp: '^sentry_dsn ='
        line: 'sentry_dsn = "{{ gitlab_runner_sentry_dsn }}"'
       insertafter: '\s*concurrent.*'
       state: present
      when: gitlab_runner_sentry_dsn != ""
      notify: restart_gitlab_runner
    - 

    16:54 $ ansible-lint site.yml 
    Traceback (most recent call last):
      File "/usr/bin/ansible-lint", line 11, in <module>
        load_entry_point('ansible-lint==3.4.20', 'console_scripts', 'ansible-lint')()
      File "/usr/lib/python2.7/dist-packages/ansiblelint/__main__.py", line 173, in main
    matches.extend(runner.run())
      File "/usr/lib/python2.7/dist-packages/ansiblelint/__init__.py", line 229, in run
        for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
      File "/usr/lib/python2.7/dist-packages/ansiblelint/utils.py", line 158, in find_children
        items = _playbook_items(playbook_ds)
      File "/usr/lib/python2.7/dist-packages/ansiblelint/utils.py", line 143, in _playbook_items
        return [item for play in pb_data for item in play.items()]
    AttributeError: 'NoneType' object has no attribute 'items'

**Comment by besmirzanaj** [comment]
`16:55 $ cat roles/riemers.gitlab-runner/tasks/global-setup.yml
---
- name: Set concurrent option
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: '^(\s*)concurrent ='
    line: '\1concurrent = {{ gitlab_runner_concurrent }}'
    state: present
    backrefs: yes
  notify: restart_gitlab_runner

- name: Add sentry dsn to config
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: '^sentry_dsn ='
    line: 'sentry_dsn = "{{ gitlab_runner_sentry_dsn }}"'
    insertafter: '\s*concurrent.*'
    state: present
  when: gitlab_runner_sentry_dsn != ""
  notify: restart_gitlab_runner
- 
`

**Comment by riemers** [comment]
Should be closed no?
