### ISSUE TITLE
The role is not compatible with Ansible <2.7 

### ISSUE THREAD

**Issue by paulrbr-fl** [riemers/ansible-gitlab-runner#61]
Hi there, I discovered that the role is not compatible with Ansible v2.0+ (< 2.7) anymore as [stated in the readme](https://github.com/riemers/ansible-gitlab-runner#requirements).

This is due to #58 which used the `access_time` (and `modification_time`) parameters of the [`file` module](https://docs.ansible.com/ansible/latest/modules/file_module.html?highlight=file) introduced in v2.7.

We could either change the code or update the Readme, as you wish @riemers.

**Comment by riemers** [comment]
well if you have the time to make it backwards compatible, go ahead. But otherwise the min is 2.7 then? 2.8.1 is latest no? I can imagine back company's that are still behind (but i would suspect those have proxy issue too)

**Comment by paulrbr-fl** [comment]
> well if you have the time to make it backwards compatible, go ahead. But otherwise the min is 2.7 then? 2.8.1 is latest no? I can imagine back company's that are still behind (but i would suspect those have proxy issue too)

Yes, oldest [supported version](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) is 2.6 right now.

I don't think we can make it backwards compatible to keep the `preserve` on `access_time` or `modification_time`. Let's bump the readme then!
