### ISSUE TITLE
Note to myself, find a way to remove the "forked from" since its obsolete

### ISSUE THREAD

**Issue by riemers** [riemers/ansible-gitlab-runner#65]
So far i think i need to remove the whole repo and recreate it. But that would also mean the travis/galaxy connections will be lost. Perhaps there is a better way.

p.s. if anyone has a good idea, please tell 👍

**Comment by Flowm** [comment]
I have previously successfully removed a fork association on a repository by writing a short message about it to the github support. [This](https://stackoverflow.com/a/16052845) SO post with link to the github help pages confirms that this still seems to be the official way.

**Comment by riemers** [comment]
Thanks for the tip! Mailed them just now. Lets see.

**Comment by riemers** [comment]
Seems to be all done now
