### ISSUE TITLE
ssh_user is not saved correctly in config.toml

### ISSUE THREAD

**Issue by crazysaem** [riemers/ansible-gitlab-runner#66]
See https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/update-config-runner.yml#L195

It says:

```
line: '  user = {{ gitlab_runner.ssh_user|default("") | to_json }}'
state: "{{ 'present' if gitlab_runner.cache_s3_insecure is defined else 'absent' }}"
```

Shouldn't it rather be? Why does `cache_s3_insecure` have to be defined for the user to be saved?

```
line: '  user = {{ gitlab_runner.ssh_user|default("") | to_json }}'
state: "{{ 'present' if gitlab_runner.ssh_user is defined else 'absent' }}"
```

**Comment by riemers** [comment]
Seems to me you find a typo

**Comment by riemers** [comment]
It is in the new code, need to get a new version out.
