### ISSUE TITLE
Role fails when using a vault-encrypted token variable

### ISSUE THREAD

**Issue by dale-c-anderson** [riemers/ansible-gitlab-runner#67]
The check for the token in tasks/main.yml produces the following error if `gitlab_runner_registration_token` is encrypted with ansible vault:

` object of type 'AnsibleVaultEncryptedUnicode' has no len()`

According to https://github.com/ansible/ansible/issues/33067, it looks like we can just throw a `|string` in there to work around it. I'll submit a PR.

**Comment by riemers** [comment]
Sounds like a plan!
