### ISSUE TITLE
Unused parameters

### ISSUE THREAD

**Issue by dolugen** [riemers/ansible-gitlab-runner#7]
Hi. I'm not using the SSH parameters in the `gitlab register` task. Basically, the command is running on a dedicated instance for a gitlab runner, so no remote connection. Is there a way to avoid using the SSH parameters? Ideally, the task should use only the parameters that have values.

**Comment by riemers** [comment]
See the merge request from markv.

**Comment by dolugen** [comment]
Thanks @markv and @riemers. Could you release a new tagged version, so it's usable with ansible-galaxy? Right now, only the v1.1.1 is installed, and I don't know how to update to trunk with galaxy.

**Comment by riemers** [comment]
My bad, should have done that on the version before too. Had a vacation too much 🍹

**Comment by dolugen** [comment]
No worries! Thanks, man.
