### ISSUE TITLE
1.4.0 not available on Ansible Galaxy

### ISSUE THREAD

**Issue by hadret** [riemers/ansible-gitlab-runner#77]
Ansible Galaxy still has the v1.3.3 showing as the latest available. Seems to me that the reason for that is the commenting out of the notification webhook in the Travis config file:

https://github.com/riemers/ansible-gitlab-runner/blob/b09dc1a70b47ffa406683b5df6cf5376198ef6a3/.travis.yml#L35

**Comment by riemers** [comment]
Your right, overlooked that one on the mac PR. Can understand why that was left out during testing ;)

**Comment by riemers** [comment]
Should be there now
