### ISSUE TITLE
Get the self signed cert from gitlab

### ISSUE THREAD

**Issue by bbaassssiiee** [riemers/ansible-gitlab-runner#84]
Is this useful in your role?

https://github.com/geerlingguy/ansible-role-gitlab/issues/127

**Comment by riemers** [comment]
Hey bbaasssssiee ;)

Perhaps, but i would say that in most cases if we need a cert from gitlab it would be fetched and installed globally on the servers instead of 1 by 1, assuming we are talking about the connectivity not borking on the ssl on first connect.

**Comment by riemers** [comment]
Think people should use the seperate role or get it globally in some other way.
