### ISSUE TITLE
How do I unregister a runner?

### ISSUE THREAD

**Issue by richard-to** [riemers/ansible-gitlab-runner#87]
This is a minor issue, but I was wondering if there was a way to unregister a runner? I set one of my runners to `state: absent`, but in my Gitlab CI/CD UI, I still my runner as registered even though it's not running on the my gitlab runner. I assumed that it would be unregistered when I set the state to `absent`.

**Comment by riemers** [comment]
Makes sense, although i never did a remove with the playbook. December is a busy month for me, i'll leave this one open for now.

**Comment by sudomabider** [comment]
Just my 2 pennies...but I think that's kinda beyond the responsibility of this role. The communication between Gitlab and its runners is always one way, i.e. the runner talks to Gitlab but not the other way round. So Gitlab would have no knowledge that the runner is gone except that it hasn't phoned home in a long time. We'd need to talk to Gitlab's API to remove it, and that's where I would probably say it's doing too much.

**Comment by riemers** [comment]
Ah, never read it that way. Would also say out of scope, so closing for now. (can understand it would be nice)

**Comment by JMLX42** [comment]
> Ah, never read it that way. Would also say out of scope, so closing for now. (can understand it would be nice)

Can we at least update [this](https://github.com/riemers/ansible-gitlab-runner/blob/master/defaults/main.yml#L68)? Because if `absent` is not meant to remove the runner, then this comment is misleading.
