### ISSUE TITLE
Multiple registration tokens?

### ISSUE THREAD

**Issue by chrisrohr** [riemers/ansible-gitlab-runner#99]
Hi, 
Thank you for this great role.  I had a question, and maybe am missing something.  It looks like the role supports multiple runners per machine, however, they all go off of the same gitlab registration token.  Am I seeing that correctly?

The issue that I'm running into is that I created a token in gitlab for a group and registered my runner just fine, however, gitlab does not allow those runners to be available to subgroups only to the projects in the group.  I was wondering if I could setup a second runner with a new registration on the same machine.

If this is not something that is supported right now and you think it is a valuable addition I could try to write up a PR for it.

Thank you

**Comment by riemers** [comment]
You can set a gitlab runner token, but if they all use the same base it does take the same one. Sadly my time is limited, in between jobs and at the moment a boiling kid at 40 degrees ;p If you can manage to whip something up or find a simply fix then that would ofcourse help.

**Comment by chrisrohr** [comment]
I can definitely take a look.  Thank you.
